# Generated by Django 5.1.7 on 2025-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentprofile_tutorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='experience_years',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='expertise',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='Temp Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subject',
            field=models.CharField(default='Temp Name', max_length=100),
            preserve_default=False,
        ),
    ]
