# Generated by Django 5.1.7 on 2025-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
    ]
