# Generated by Django 5.1.7 on 2025-05-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_delete_course_remove_tutorprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(default='Undecided', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Undecided', max_length=50),
        ),
    ]
